### ISSUE TITLE
Personvern må oppdateres med ny dato

### ISSUE THREAD

**Issue by nfkleven** [SigurdMW/din-advent#38]
https://wwwtest.dinadvent.no/privacy 

- Må oppdatere dato for når ting skal slettes. (Nå står det 2019)
- I tillegg burde vi skrive om slik at det står at "vi sletter alt lagrede kalenderinnhold utenom brukeren"

**Comment by SigurdMW** [comment]
Duplikat av #37 @nfkleven ? Spør om det samme - skal alt slettes?

**Comment by nfkleven** [comment]
Synes den ser greit ut nå. Lukker denne saken.
