### ISSUE TITLE
Ny sidelastning og “hakete opplevelse” når mottaker trykker på rute i mottatt kalender

### ISSUE THREAD

**Issue by nfkleven** [SigurdMW/din-advent#40]
Se video her: https://drive.google.com/file/d/1oyym-ZuOJ6D9dyrW7vkRfTGY5oINlBCR/view?usp=sharing

**Comment by SigurdMW** [comment]
Hmm kan gjøre noe med dette, men det skal bare være første gang du går fra en kalender og til en kalenderluke. Når du da går tilbake til kalender skal neste kalenderlukeåpning være smuudere. Stemmer det @nfkleven ?

**Comment by nfkleven** [comment]
Jeg fant ut av hva dette var. Det er pga ulike størrelser i HTML element i meny-knapper øverst til høyre. Den skifter fra "Logg inn" til Nisse-symbol. Men dette kommer ikke til å skje mottakeren. Jeg lukker denne da dette ikke vil bli et reellt problem.
