### ISSUE TITLE
Forvirrende tilbakemelding om "ikke valgt pakke enda"

### ISSUE THREAD

**Issue by nfkleven** [SigurdMW/din-advent#43]
Jeg har starter pakke med 1 kalender. Jeg har allerede en kalender som har en delt lenke. Nå har jeg også en kalender nr.2. Når jeg prøver å lage en dele-url på denne, så får jeg opp feilmeldingen gitt i bildet. Kunne man her heller gitt en mer korrekt tilbakemelding som sier at vi allerede har brukt opp den nåværende pakken vår?
<img width="1094" alt="Screenshot 2020-10-18 at 22 13 51" src="https://user-images.githubusercontent.com/1074873/96378887-72443400-118f-11eb-9776-94ba18689ddb.png">

**Comment by SigurdMW** [comment]
@nfkleven jeg klarer ikke å gjenskape denne, jeg får denne feilmelding i det scenario du har beskrevet: 
![image](https://user-images.githubusercontent.com/6359003/96840397-b1ea7480-144a-11eb-9230-73ec5ec457ec.png)

**Comment by SigurdMW** [comment]
Fant feilen! Var fordi man måtte logge inn og ut før rett pakke ble registrert. Kan retestes i test med ny bruker, gjennomføre kjøp og så forsøke å dele kalender (uten å logge ut el i mellom) @nfkleven

**Comment by nfkleven** [comment]
@SigurdMW Denne er ikke helt rettet enda. Jeg lukke denne, og har laget en ny beskrivelse i trello: 
https://trello.com/c/s65RpFJI/78-missvisende-feilmelding-n%C3%A5r-jeg-pr%C3%B8ver-%C3%A5-dele-min-andre-kalender-selv-om-jeg-har-starter-pakken
