### ISSUE TITLE
reCaptcha ødelegger god brukeropplevelse

### ISSUE THREAD

**Issue by nfkleven** [SigurdMW/din-advent#50]
Jeg tror vi burde vurdere å droppe den recaptcha da den er et veldig irriterende moment når man logger inn. Det å bli møtt slikt er ikke bra (se skjermbilde), og tjenesten vår er vel heller ikke så utsatt? Eventuelt om man kunne brukt en enklere metode hvis mulig?
<img width="1433" alt="Screenshot 2020-10-21 at 21 09 42" src="https://user-images.githubusercontent.com/1074873/96771298-c2b2d000-13e1-11eb-9db0-9d6def19f616.png">

**Comment by SigurdMW** [comment]
Det er bare det at man kan enkel få automatiske script som kjører mot siden vår og spammer brukeren med innloggingsforespørsler. Det kan føre til:
1) Database blir fylt opp og vi må oppgradere til en større plan
2) mailservicen vi bruker koster mer penger
3) brukere vil spammes, fryktelig irriterende

Håper de fleste bruker facebook / google, så da er det ikke noe problem. Dessuten tror jeg folk er vant med recptcha fra før. Ok @nfkleven ?

**Comment by nfkleven** [comment]
Ja, ser argumentene for det. Men er det mulig med slik enklere recaptcha man bare trenger å huke av? (Uten å markere ulike bilder av ting som de spør om?) Hvis ikke, la den være som den er. Vi krysser fingrene for at flest bruker Google og Facebook sign-in 🤞

**Comment by SigurdMW** [comment]
For folk med mer vanlig bruksmønster vil ikke recaptcha trigge at du må velge bilder så ofte. Vi blir utsatt fordi vi tester og logger uvanlig mye inn og ut. På mobilen min får jeg feks aldri spørsmål om bilder, for den brukes ikke så mye til test. Desktopen derimot, der blir jeg spurt stadig vekk :)
