### ISSUE TITLE
Tannhjul (innstillinger - ikonet på kalenderside) følger ikke fargetema

### ISSUE THREAD

**Issue by nfkleven** [SigurdMW/din-advent#51]
Denne burde følge fargetema som resten av lukene og tittel
<img width="159" alt="Screenshot 2020-10-21 at 21 19 52" src="https://user-images.githubusercontent.com/1074873/96772366-533de000-13e3-11eb-96df-6fd46cf7c20f.png">

**Comment by SigurdMW** [comment]
Fjernet derfra i test, så lukker bug @nfkleven
